//! Validation harness CLI.
//!
//!   cargo run -p rl_car_validate --release -- gen      # write scenarios, run RocketSim oracle -> traces
//!   cargo run -p rl_car_validate --release -- report   # compare core vs traces, write VALIDATION.md
//!   cargo run -p rl_car_validate --release -- dump <scenario>   # write the core's trajectory CSV
//!   cargo run -p rl_car_validate --release            # gen (if the oracle is built) + report

use rl_car_validate::scenarios::{self, Category};
use rl_car_validate::*;
use std::fmt::Write as _;
use std::process::Command;

fn oracle_exe() -> std::path::PathBuf {
    if let Ok(p) = std::env::var("ROCKETSIM_ORACLE") {
        return p.into();
    }
    let base = workspace_root().join("oracle").join("build").join("rocketsim_oracle");
    if cfg!(windows) { base.with_extension("exe") } else { base }
}

fn generate() -> Result<(), String> {
    let exe = oracle_exe();
    if !exe.exists() {
        return Err(format!("oracle not found at {} (build it with oracle/build.sh)", exe.display()));
    }
    std::fs::create_dir_all(validation_dir().join("scenarios")).map_err(|e| e.to_string())?;
    std::fs::create_dir_all(validation_dir().join("traces")).map_err(|e| e.to_string())?;
    for sc in scenarios::all() {
        let sp = scenario_path(&sc.name);
        std::fs::write(&sp, sc.to_oracle_text()).map_err(|e| e.to_string())?;
        let status = Command::new(&exe).arg(&sp).arg(trace_path(&sc.name)).status().map_err(|e| e.to_string())?;
        if !status.success() {
            return Err(format!("oracle failed on {}", sc.name));
        }
        println!("oracle: {}", sc.name);
    }
    Ok(())
}

fn fmt_f(v: f32) -> String {
    if v < 0.001 {
        format!("{v:.1e}")
    } else if v < 10.0 {
        format!("{v:.3}")
    } else {
        format!("{v:.1}")
    }
}

fn report() -> Result<bool, String> {
    let mut rows = String::new();
    let mut all_pass = true;
    let mut counts = std::collections::BTreeMap::<&str, (u32, u32)>::new();
    println!("{:<24} {:>5} {:>10} {:>10} {:>9} {:>9} {:>6} {:>5}  result", "scenario", "ticks", "pos(uu)", "vel(uu/s)", "rot(deg)", "angv", "flags", "div@");
    for sc in scenarios::all() {
        let text = std::fs::read_to_string(trace_path(&sc.name)).map_err(|e| format!("{}: {e} (run `gen` first)", sc.name))?;
        let oracle = parse_trace(&text)?;
        let core = run_core(&sc);
        let cmp = compare(&core, &oracle, sc.compare_ticks);
        let tol = tolerance(sc.category);
        let pass = cmp.passes(tol);
        all_pass &= pass;
        let e = counts.entry(sc.category.name()).or_default();
        e.0 += pass as u32;
        e.1 += 1;
        let div = cmp.diverge_tick.map_or("-".to_string(), |t| t.to_string());
        println!(
            "{:<24} {:>5} {:>10} {:>10} {:>9} {:>9} {:>6} {:>5}  {}",
            sc.name,
            cmp.ticks,
            fmt_f(cmp.max_pos),
            fmt_f(cmp.max_vel),
            fmt_f(cmp.max_rot_deg),
            fmt_f(cmp.max_ang_vel),
            cmp.flag_mismatches,
            div,
            if pass { "PASS" } else { "FAIL" }
        );
        writeln!(
            rows,
            "| `{}` | {} | {} | {} | {} | {} | {} | {} | {} | {} | {} |",
            sc.name,
            sc.category.name(),
            cmp.ticks,
            fmt_f(cmp.max_pos),
            fmt_f(cmp.max_vel),
            fmt_f(cmp.max_rot_deg),
            fmt_f(cmp.max_ang_vel),
            fmt_f(cmp.max_boost),
            cmp.flag_mismatches,
            div,
            if pass { "pass" } else { "**FAIL**" }
        )
        .unwrap();
    }

    let mut md = String::new();
    writeln!(md, "# Validation report\n").unwrap();
    writeln!(md, "Generated by `cargo run -p rl_car_validate --release -- report`. Do not edit by hand.\n").unwrap();
    writeln!(md, "Every scenario is run twice from the same initial state with the same per-tick controls: once").unwrap();
    writeln!(md, "through **RocketSim** (the oracle, `oracle/`, pinned commit) and once through `rl_car_core`, both in a").unwrap();
    writeln!(md, "world of identical static planes. All errors are the **maximum over every compared tick** (120 Hz).\n").unwrap();
    writeln!(md, "## Summary\n").unwrap();
    writeln!(md, "| category | passed | tolerance (max pos / vel / rot / ang vel) |").unwrap();
    writeln!(md, "|---|---|---|").unwrap();
    for cat in [Category::Ground, Category::Air, Category::Wall, Category::Body] {
        let (p, n) = counts.get(cat.name()).copied().unwrap_or_default();
        let t = tolerance(cat);
        writeln!(md, "| {} | {p}/{n} | {} uu / {} uu/s / {}° / {} rad/s |", cat.name(), t.pos, t.vel, t.rot_deg, t.ang_vel).unwrap();
    }
    writeln!(md, "\n## Per scenario\n").unwrap();
    writeln!(md, "Columns: compared ticks, max position error, max velocity error, max orientation error, max angular").unwrap();
    writeln!(md, "velocity error, max boost-amount error, ticks with differing state flags (on_ground / has_jumped /").unwrap();
    writeln!(md, "has_double_jumped / has_flipped), first tick with position error > 1 uu.\n").unwrap();
    writeln!(md, "| scenario | category | ticks | pos (uu) | vel (uu/s) | rot (°) | ang vel (rad/s) | boost | flag diffs | > 1 uu at | result |").unwrap();
    writeln!(md, "|---|---|---|---|---|---|---|---|---|---|---|").unwrap();
    md.push_str(&rows);
    writeln!(md, "\n## Scenario descriptions\n").unwrap();
    for sc in scenarios::all() {
        writeln!(md, "- `{}` — {}", sc.name, sc.description).unwrap();
    }
    std::fs::write(validation_dir().join("REPORT.md"), md).map_err(|e| e.to_string())?;
    println!("\nwrote {}", validation_dir().join("REPORT.md").display());
    Ok(all_pass)
}

fn dump(name: &str) -> Result<(), String> {
    let sc = scenarios::all().into_iter().find(|s| s.name == name).ok_or("unknown scenario")?;
    let core = run_core(&sc);
    let mut out = String::from("tick,px,py,pz,vx,vy,vz,wx,wy,wz,fx,fy,fz,rx,ry,rz,ux,uy,uz,boost,on_ground,has_jumped,has_double_jumped,has_flipped,c0,c1,c2,c3\n");
    for s in core {
        let v = |v: Vec3| format!("{},{},{}", v.x, v.y, v.z);
        writeln!(
            out,
            "{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{}",
            s.tick,
            v(s.pos),
            v(s.vel),
            v(s.ang_vel),
            v(s.rot.col(0)),
            v(s.rot.col(1)),
            v(s.rot.col(2)),
            s.boost,
            s.on_ground as i32,
            s.has_jumped as i32,
            s.has_double_jumped as i32,
            s.has_flipped as i32,
            s.contacts[0] as i32,
            s.contacts[1] as i32,
            s.contacts[2] as i32,
            s.contacts[3] as i32
        )
        .unwrap();
    }
    let p = validation_dir().join(format!("{name}.core.csv"));
    std::fs::write(&p, out).map_err(|e| e.to_string())?;
    println!("wrote {}", p.display());
    Ok(())
}

use rl_car_core::Vec3;

fn main() {
    let args: Vec<String> = std::env::args().skip(1).collect();
    let res = match args.first().map(String::as_str) {
        Some("gen") => generate().map(|_| true),
        Some("report") => report(),
        Some("ball") => ball_report(),
        Some("dump") => dump(args.get(1).map(String::as_str).unwrap_or("")).map(|_| true),
        None => {
            if oracle_exe().exists() {
                generate().and_then(|_| report())
            } else {
                eprintln!("(oracle not built; comparing against committed traces)");
                report()
            }
        }
        Some(other) => Err(format!("unknown command {other}")),
    };
    match res {
        Ok(true) => {}
        Ok(false) => std::process::exit(2),
        Err(e) => {
            eprintln!("error: {e}");
            std::process::exit(1);
        }
    }
}

fn ball_report() -> Result<bool, String> {
    use rl_car_validate::ball_scenarios as bs;
    let exe = oracle_exe();
    let mut ok = true;
    println!("{:<24} {:>9} {:>10} {:>8} {:>5} | {:>9} {:>10} {:>8} {:>5}", "scenario", "ball pos", "ball vel", "ball w", "div@", "car pos", "car vel", "car rot", "div@");
    for sc in bs::all() {
        let sp = scenario_path(sc.name());
        let tp = trace_path(sc.name());
        if exe.exists() {
            std::fs::write(&sp, sc.to_oracle_text()).map_err(|e| e.to_string())?;
            let status = Command::new(&exe).arg(&sp).arg(&tp).status().map_err(|e| e.to_string())?;
            if !status.success() {
                return Err(format!("oracle failed on {}", sc.name()));
            }
        }
        let text = std::fs::read_to_string(&tp).map_err(|e| format!("{}: {e}", sc.name()))?;
        let oracle = bs::parse_ball_trace(&text)?;
        let core = bs::run_core(&sc);
        let c = bs::compare_ball(&sc, &core, &oracle);
        let pass = bs::passes(&c);
        ok &= pass;
        let div = |d: Option<u32>| d.map_or("-".to_string(), |t| t.to_string());
        let (cp, cv, cr, cd) = c.car.as_ref().map_or(("-".into(), "-".into(), "-".into(), "-".into()), |k| (fmt_f(k.max_pos), fmt_f(k.max_vel), fmt_f(k.max_rot_deg), div(k.diverge_tick)));
        println!("{:<24} {:>9} {:>10} {:>8} {:>5} | {:>9} {:>10} {:>8} {:>5}  {}", sc.name(), fmt_f(c.max_pos), fmt_f(c.max_vel), fmt_f(c.max_ang_vel), div(c.diverge_tick), cp, cv, cr, cd, if pass { "PASS" } else { "FAIL" });
    }
    Ok(ok)
}
